_target_: stream3r.models.multiview_dust3r_module.MultiViewDUSt3RLitModule

pretrained: null
resume_from_checkpoint: ${ckpt_path}

eval_use_pts3d_from_local_head: true

train_criterion:
  _target_: stream3r.loss.losses.CausalLoss

validation_criterion:
  _target_: stream3r.loss.losses.CausalLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas: 
    - 0.9
    - 0.95
  weight_decay: 0.05

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 10
  max_epochs: ${trainer.max_epochs}
  eta_min: 1e-06

net:
  _target_: stream3r.models.stream3r.STream3R


# compile model for faster training with pytorch 2.0
compile: false
